server:
  port: 9992


spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9991
          predicates:
            - Path=/auth-service/**
        - id: customer-service
          uri: http://localhost:9994
          predicates:
            - Path=/customer-service/**
          filters:
            - name: AuthenticationFilter

app:
  secret: mySecretKeymySecretKeymySecretKeymySecretKeymySecretKeymySecretKeymySecretKeymySecretKeymySecretKeymySecretKey



